name: Deploy from development

on: [push]

jobs:

  send_message:
      runs-on: ubuntu-latest
      steps:
          - name: send message
            uses: appleboy/telegram-action@master
            with:
              to: ${{ secrets.TELEGRAM_TO }}
              token: ${{ secrets.TELEGRAM_TOKEN }}
              message: |+
                OK ^_^
                ${{ github.repository }}
                (${{ github.actor }})
                - pushed on git:
                  << ${{ github.event.head_commit.message }} >>